-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema simulado_saep_02
-- -----------------------------------------------------
-- DROP SCHEMA simulado_saep_02;
CREATE SCHEMA IF NOT EXISTS `simulado_saep_02` DEFAULT CHARACTER SET utf8 ;
USE `simulado_saep_02` ;

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `insumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumos` (
  `idinsumos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NOT NULL,
  `quantidade_minima` INT NOT NULL,
  `quantidade` INT NULL,
  `categoria` VARCHAR(100) NOT NULL,
  `custo` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idinsumos`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `movimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movimentacao` (
  `idmovimentacao` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `quantidade` INT NOT NULL,
  `tipo` INT NOT NULL COMMENT '0-saida, 1-entrada',
  `usuarios_idusuarios` INT NOT NULL,
  `insumos_idinsumos` INT NOT NULL,
  PRIMARY KEY (`idmovimentacao`),
  INDEX `fk_movimentacao_usuarios_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  INDEX `fk_movimentacao_insumos1_idx` (`insumos_idinsumos` ASC) VISIBLE,
  CONSTRAINT `fk_movimentacao_usuarios`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimentacao_insumos1`
    FOREIGN KEY (`insumos_idinsumos`)
    REFERENCES `insumos` (`idinsumos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- ---------------------------------------
-- INSERÇÕES
-- ---------------------------------------

INSERT IGNORE INTO usuarios (idusuarios, nome, email, senha) VALUES 
  (1, 'José', 'jose@gmail.com', '244466666'), 
  (2, 'Leandro', 'leandro_carvalho@gmail.com', 'Senha'), 
  (3, 'Irineu', 'irineu@gmail.com', '123456789');

INSERT IGNORE INTO insumos (idinsumos, nome, quantidade, categoria, custo, quantidade_minima) VALUES
  (1, 'Aço Galvanizado', 20, 'Chapas', 150.00, 10),
  (2, 'Tinta Esmalte', 10, 'Tintas', 30.00, 2),
  (3, 'Parafuso', 500, 'Peças', 2.00, 50);

INSERT IGNORE INTO movimentacao (idmovimentacao, data, quantidade, tipo, usuarios_idusuarios, insumos_idinsumos) VALUES
  (1, STR_TO_DATE('04/01/2026 08:30:00', '%d/%m/%Y %H:%i:%s'), 5, 1, 1, 1),
  (2, STR_TO_DATE('05/02/2026 14:15:00', '%d/%m/%Y %H:%i:%s'), 10, 1, 1, 2),
  (3, STR_TO_DATE('06/03/2026 16:45:00', '%d/%m/%Y %H:%i:%s'), 50, 0, 1, 3);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;